### ISSUE TITLE
Multiword job name

### ISSUE THREAD

**Issue by pszafer** [arogarth/nagios-check_bareos#2]
Hello,
I know that this plugin is old, but maybe someone would find it useful like I do.
Thanks for that.

But there is requirment that job name is one word only.
If you want to change it you have to modify $cmd line like this:

```
my $cmd = "echo \"list job=\\\"${job}\\\"\" | bconsole -c ${workingDir}/nagios-console.conf";  
```

**Comment by arogarth** [comment]
Hi, thank you. I fixed it in 40667b0
